/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as Unclicked100RouteImport } from './routes/unclicked-100'
import { Route as TailorRouteImport } from './routes/tailor'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EmailfinderRouteImport } from './routes/emailfinder'
import { Route as IndexRouteImport } from './routes/index'

const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const Unclicked100Route = Unclicked100RouteImport.update({
  id: '/unclicked-100',
  path: '/unclicked-100',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorRoute = TailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailfinderRoute = EmailfinderRouteImport.update({
  id: '/emailfinder',
  path: '/emailfinder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emailfinder': typeof EmailfinderRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tailor': typeof TailorRoute
  '/unclicked-100': typeof Unclicked100Route
  '/weekly': typeof WeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emailfinder': typeof EmailfinderRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tailor': typeof TailorRoute
  '/unclicked-100': typeof Unclicked100Route
  '/weekly': typeof WeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emailfinder': typeof EmailfinderRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/tailor': typeof TailorRoute
  '/unclicked-100': typeof Unclicked100Route
  '/weekly': typeof WeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emailfinder'
    | '/feed'
    | '/settings'
    | '/skills'
    | '/tailor'
    | '/unclicked-100'
    | '/weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emailfinder'
    | '/feed'
    | '/settings'
    | '/skills'
    | '/tailor'
    | '/unclicked-100'
    | '/weekly'
  id:
    | '__root__'
    | '/'
    | '/emailfinder'
    | '/feed'
    | '/settings'
    | '/skills'
    | '/tailor'
    | '/unclicked-100'
    | '/weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailfinderRoute: typeof EmailfinderRoute
  FeedRoute: typeof FeedRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TailorRoute: typeof TailorRoute
  Unclicked100Route: typeof Unclicked100Route
  WeeklyRoute: typeof WeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unclicked-100': {
      id: '/unclicked-100'
      path: '/unclicked-100'
      fullPath: '/unclicked-100'
      preLoaderRoute: typeof Unclicked100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor': {
      id: '/tailor'
      path: '/tailor'
      fullPath: '/tailor'
      preLoaderRoute: typeof TailorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emailfinder': {
      id: '/emailfinder'
      path: '/emailfinder'
      fullPath: '/emailfinder'
      preLoaderRoute: typeof EmailfinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailfinderRoute: EmailfinderRoute,
  FeedRoute: FeedRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TailorRoute: TailorRoute,
  Unclicked100Route: Unclicked100Route,
  WeeklyRoute: WeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
