import {useEffect,useState} from 'react';
import {getTailorServerBase} from '../utils/tailorServer';
import './ai-usage.css';
export function aiUsageSession(){let id=sessionStorage.getItem('atriveo-ai-usage-session');if(!id){id=crypto.randomUUID();sessionStorage.setItem('atriveo-ai-usage-session',id);}return id;}
type WindowUsage={bucket:string;window:string;remainingPercent:number;durationMinutes:number|null;resetsAt:number|null};
type Usage={online:boolean;codex:{windows:WindowUsage[];checkedAt:string}|null;totals:Record<string,{tokens:number;requests:number}>};
export default function AiUsage(){
 const [usage,setUsage]=useState<Usage|null>(null),[open,setOpen]=useState(false);
 useEffect(()=>{let active=true;const refresh=async()=>{try{const r=await fetch(`${getTailorServerBase()}/resume-builder/ai-usage`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:aiUsageSession()})});if(r.ok){const d=await r.json();if(active&&d.ok&&d.totals)setUsage(d);}}catch{}};void refresh();const timer=setInterval(()=>void refresh(),30000);return()=>{active=false;clearInterval(timer);};},[]);
 const stale=!usage?.codex||Date.now()-new Date(usage.codex.checkedAt).getTime()>120000;
 const primary=usage?.codex?.windows.find(w=>w.bucket==='codex'&&w.window==='primary');
 return <div className="ai-usage"><button className="ai-usage-button" aria-expanded={open} onClick={()=>setOpen(!open)}>✦ {primary&&!stale&&usage?.online?`Codex ${primary.remainingPercent}% left`:'AI usage'}</button>{open&&<><button className="ai-usage-back" aria-label="Close AI usage" onClick={()=>setOpen(false)}/><section className="ai-usage-panel" aria-label="AI usage"><header><b>AI allowance</b><button aria-label="Close usage" onClick={()=>setOpen(false)}>×</button></header><small>{usage?.online?'Mac connected':'Mac offline · usage may be out of date'}</small><article><b>Codex / ChatGPT</b>{usage?.codex?.windows.length?usage.codex.windows.map(w=><div key={w.bucket+w.window}><div className="ai-usage-row"><span>{w.bucket!=='codex'?`${w.bucket} · `:''}{w.durationMinutes===10080?'Weekly':w.durationMinutes?`${w.durationMinutes/60}-hour window`:w.window}</span><strong>{w.remainingPercent}% left{stale?' · last known':''}</strong></div><progress max={100} value={w.remainingPercent}/>{w.resetsAt&&<small>Resets {new Date(w.resetsAt*1000).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small>}</div>):<small>Remaining allowance unavailable</small>}<a href="https://chatgpt.com/codex/settings/usage" target="_blank" rel="noreferrer">Open subscription usage ↗</a></article><article><b>Claude</b><small>Remaining allowance isn’t reported by this connection.</small><a href="https://claude.ai/settings/usage" target="_blank" rel="noreferrer">Check Claude allowance ↗</a></article><article><b>This dashboard session</b>{['claude','codex'].map(p=><div className="ai-usage-row" key={p}><span>{p==='claude'?'Claude':'Codex'}</span><strong>{(usage?.totals?.[p]?.tokens||0).toLocaleString()} tokens used</strong></div>)}<small>Measured AI Help calls in this tab since tracking began. Includes input, output and cached input. Not your subscription’s remaining balance.</small></article></section></>}</div>;
}
