import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';
const requireEngine=createRequire(path.join(process.env.PLAYATRIVEO_DIR||path.join(os.homedir(),'playatriveo'),'package.json'));const {chromium}=requireEngine('playwright');
const root=path.resolve(import.meta.dirname,'../..');
const before='Constructed Python ingestion workflows across 13 evaluation sessions with validated data for financial analysis in production.';
const after='Managed FinBERT sentiment models on AWS Bedrock A100 GPUs with MLflow, scoring 110+ Fed events yearly since 2019 as each press conference goes live.';
async function fixture(mobile=false){
 const server=http.createServer((req,res)=>{let file=path.join(root,'dist-apply',new URL(req.url,'http://x').pathname);if(!fs.existsSync(file)||!fs.statSync(file).isFile())file=path.join(root,'dist-apply/index.html');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}});const errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));let jdVersion='jd1';
 const sections=[{role:'stony-brook',kind:'experience',label:'Stony Brook',bullets:[{ac_id:'AC-001',facet:'default',text:before}],stack:['Python']}];
 const loaded={source:{kind:'job',jobUrl:'https://example.test/job',title:'Backend Engineer',company:'Test'},headerTitle:'Backend Engineer',email:'locked@example.test',city:'Locked City',skills:['Languages: Python'],sections,options:{'stony-brook':[]},roles:[{role:'stony-brook',kind:'experience',label:'Stony Brook'}],current:{pdfPath:'/fixture.pdf',edited:false,generatedPdfPath:null},jd:'MLflow required',layout:{name:'Locked Name',phone:'555-0000',linkedin:'locked-link',github:'locked-github',education:[{school:'Locked University',degree:'Locked Degree',place:'Locked Place',dates:'Locked Dates'}],roles:{'stony-brook':{name:'Stony Brook',dates:'Locked Dates',place:'Locked City',order:0,title:null}},projects:{},sbTitleOverrides:{}}};
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.pathname==='/api/auth/me')return route.fulfill({json:{user:{id:1,name:'Test',email:'test@example.test'}}});if(u.pathname==='/applications/review-queue')return route.fulfill({json:{ok:true,counts:{unanswered:0,ready:0},unanswered:[],cards:[]}});
 if(u.pathname.startsWith('/resume-builder/')){const op=u.pathname.split('/').at(-1),body=route.request().postData()?route.request().postDataJSON():{};calls.push({op,body});if(op==='load')return route.fulfill({json:loaded});if(op==='ai-version')return route.fulfill({json:{ok:true,jdVersion}});if(op==='ai-match'){const current=body.sections[0];const suggestions=current.bullets[0].text===after?[]:[{id:'section-change',kind:'section',si:0,bi:-1,current:current.bullets[0].text,suggested:after,originalHashInput:JSON.stringify(current.bullets),bullets:[{ac_id:'AC-199',facet:'live-mlops',text:after}],reason:'Approved model operations evidence.',requirements:['MLflow'],evidence_source:['story_bank:AC-199:0']},{id:'skills-change',kind:'skills',si:-1,bi:-1,current:body.skills.join('\n'),suggested:'AI & Machine Learning: MLflow',skills:['AI & Machine Learning: MLflow'],reason:'Supported skill',requirements:[],evidence_source:['story_bank:AC-199:0']}];return route.fulfill({json:{ok:true,analysis:{id:'a',original_match_score:60,optimized_match_score:80,score:60,subscores:{skills:60,experience:60,keywords:60,evidence:60},requirements:[],suggestions,atsProblems:[],resumeVersion:'rv',jdVersion:'jd1',rejected:[]}}});}if(op==='render')return route.fulfill({json:{ok:true,draftId:'draft',pdfPath:'/draft.pdf',pages:1,problems:[],jdMatch:null}});if(op==='check')return route.fulfill({json:{ok:true,issues:[],freeVerbs:[]}});return route.fulfill({json:{ok:true}});}
 if(u.hostname==='cdn.jsdelivr.net')return route.fulfill({contentType:'text/css',body:''});if(u.origin===base)return route.continue();return route.abort();});
 return {page,base,calls,errors,setJd:v=>jdVersion=v,close:async()=>{await browser.close();await new Promise(r=>server.close(r));}};
}
test('Apply All updates editor and existing live preview; Undo restores content; Save is separate',async()=>{const f=await fixture();try{await f.page.goto(f.base+'/resume_builder?job=https%3A%2F%2Fexample.test%2Fjob');await f.page.getByRole('button',{name:'✦ AI Match',exact:true}).click();await f.page.getByRole('button',{name:'Optimize Resume',exact:true}).click();await f.page.getByRole('button',{name:'Apply All (2)',exact:true}).click();await f.page.locator('.rb-editor').getByText(after,{exact:false}).waitFor();assert(await f.page.locator('.rb-skills textarea').inputValue().then(v=>v.includes('MLflow')));await f.page.getByRole('button',{name:'Close AI Match'}).click();await f.page.frameLocator('iframe.rb-live').getByText(after,{exact:false}).first().waitFor();await f.page.getByRole('button',{name:'Undo',exact:true}).click();await f.page.locator('.rb-editor').getByText(before,{exact:false}).waitFor();assert.equal(f.calls.filter(c=>c.op==='save').length,0);const renders=f.calls.filter(c=>c.op==='render');for(const r of renders){assert.equal(r.body.headerTitle,'Backend Engineer');assert.equal(r.body.email,'locked@example.test');assert.equal(r.body.city,'Locked City');assert.equal(r.body.sections[0].role,'stony-brook');assert.deepEqual(r.body.sections[0].stack,['Python']);}assert.deepEqual(f.errors,[]);}finally{await f.close();}});
test('mobile review exposes Apply All without copy/paste and model dialog stays within viewport',async()=>{const f=await fixture(true);try{await f.page.goto(f.base+'/resume_builder?job=x');await f.page.getByRole('button',{name:'✦ AI Match',exact:true}).click();await f.page.getByRole('button',{name:'Optimize Resume',exact:true}).click();const panel=f.page.getByRole('dialog',{name:'AI resume match'});await panel.getByRole('button',{name:'Apply All (2)',exact:true}).waitFor();const b=await panel.boundingBox();assert(b.x>=0&&b.width<=390);assert.deepEqual(f.errors,[]);}finally{await f.close();}});
