import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';
const requireEngine=createRequire(path.join(process.env.PLAYATRIVEO_DIR||path.join(os.homedir(),'playatriveo'),'package.json'));const {chromium}=requireEngine('playwright');
const root=path.resolve(import.meta.dirname,'../..');
const before='Constructed Python ingestion workflows across 13 evaluation sessions with validated data for financial analysis in production.';
const after='Managed FinBERT sentiment models on AWS Bedrock A100 GPUs with MLflow, scoring 110+ Fed events yearly since 2019 as each press conference goes live.';
async function fixture(mobile=false,general=false){
 const server=http.createServer((req,res)=>{let file=path.join(root,'dist-apply',new URL(req.url,'http://x').pathname);if(!fs.existsSync(file)||!fs.statSync(file).isFile())file=path.join(root,'dist-apply/index.html');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}});const errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));let jdVersion='jd1';
 const sections=[{role:'stony-brook',kind:'experience',label:'Stony Brook',bullets:[{ac_id:'AC-001',facet:'default',text:before}],stack:['Python']}];
 const loaded={source:{kind:'job',jobUrl:'https://example.test/job',title:'Backend Engineer',company:'Test'},headerTitle:'Backend Engineer',email:'locked@example.test',city:'Locked City',skills:['Languages: Python'],sections,options:{'stony-brook':[]},roles:[{role:'stony-brook',kind:'experience',label:'Stony Brook'}],current:{pdfPath:'/fixture.pdf',edited:false,generatedPdfPath:null},jd:'MLflow required',layout:{name:'Locked Name',phone:'555-0000',linkedin:'locked-link',github:'locked-github',education:[{school:'Locked University',degree:'Locked Degree',place:'Locked Place',dates:'Locked Dates'}],roles:{'stony-brook':{name:'Stony Brook',dates:'Locked Dates',place:'Locked City',order:0,title:null}},projects:{},sbTitleOverrides:{}}};
 if(general){loaded.source={kind:'track',track:'data-analyst'};loaded.jd=null;}
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.pathname==='/api/auth/me')return route.fulfill({json:{user:{id:1,name:'Test',email:'test@example.test'}}});if(u.pathname==='/applications/review-queue')return route.fulfill({json:{ok:true,counts:{unanswered:0,ready:0},unanswered:[],cards:[]}});
 if(u.pathname==='/staffing/status')return route.fulfill({json:{sources:[],runs:[],schedule:{label:'Daily',next_at:new Date().toISOString()},total_jobs:2}});
 if(u.pathname==='/staffing/workspace')return route.fulfill({json:{jobs:[{_id:'ready',title:'Ready role',company:'Company',location:'NY',job_url:'https://example.test/job',resume:'/fixture.pdf',state:'new',eligible:true,reasons:[],first_seen_at:new Date().toISOString()},{_id:'missing',title:'Missing resume role',company:'Company',location:'NY',job_url:'https://example.test/missing',state:'new',eligible:true,reasons:[],first_seen_at:new Date().toISOString()}],total:2,counts:{recommended:2,saved:0,applied:0,all:2}}});
 if(u.pathname==='/staffing/prepare'){calls.push({op:'staffing-prepare',body:route.request().postDataJSON()});return route.fulfill({json:{ok:true,resume:'/fixture.pdf',builder_id:'prepared-resume'}});}
 if(u.pathname.startsWith('/resume-builder/')){const op=u.pathname.split('/').at(-1),body=route.request().postData()?route.request().postDataJSON():{};calls.push({op,body});if(op==='ai-usage')return route.fulfill({json:{ok:true,online:true,codex:{windows:[{bucket:'codex',window:'primary',remainingPercent:55,durationMinutes:300,resetsAt:Math.floor(Date.now()/1000)+3600}],checkedAt:new Date().toISOString()},totals:{claude:{tokens:1200,requests:1},codex:{tokens:500,requests:1}}}});if(op==='load')return route.fulfill({json:loaded});if(op==='ai-version')return route.fulfill({json:{ok:true,jdVersion}});if(op==='ai-result')return route.fulfill({json:{status:'done',analysis:{answer:'Your current resume demonstrates Python experience.'}}});if(op==='ai-match'){if(body.mode==='question')return route.fulfill({json:{jobId:'question-job'}});const current=body.sections[0];const suggestions=current.bullets[0].text===after?[]:[{id:'section-change',kind:'section',si:0,bi:-1,current:current.bullets[0].text,suggested:after,originalHashInput:JSON.stringify(current.bullets),bullets:[{ac_id:'AC-199',facet:'live-mlops',text:after}],reason:'Approved model operations evidence.',requirements:['MLflow'],evidence_source:['story_bank:AC-199:0']},{id:'skills-change',kind:'skills',si:-1,bi:-1,current:body.skills.join('\n'),suggested:'AI & Machine Learning: MLflow',skills:['AI & Machine Learning: MLflow'],reason:'Supported skill',requirements:[],evidence_source:['story_bank:AC-199:0']}];return route.fulfill({json:{ok:true,analysis:{id:'a',original_match_score:60,optimized_match_score:80,score:60,subscores:{skills:60,experience:60,keywords:60,evidence:60},requirements:[],suggestions,atsProblems:[],resumeVersion:'rv',jdVersion:'jd1',rejected:[]}}});}if(op==='render')return route.fulfill({json:{ok:true,draftId:'draft',pdfPath:'/draft.pdf',pages:1,problems:[],jdMatch:null}});if(op==='check')return route.fulfill({json:{ok:true,issues:[],freeVerbs:[]}});return route.fulfill({json:{ok:true}});}
 if(u.hostname==='cdn.jsdelivr.net')return route.fulfill({contentType:'text/css',body:''});if(u.origin===base)return route.continue();return route.abort();});
 return {page,base,calls,errors,setJd:v=>jdVersion=v,close:async()=>{await browser.close();await new Promise(r=>server.close(r));}};
}
test('Apply All updates editor and existing live preview; Undo restores content; Save is separate',async()=>{const f=await fixture();try{await f.page.goto(f.base+'/resume_builder?job=https%3A%2F%2Fexample.test%2Fjob');await f.page.getByRole('button',{name:'AI Help',exact:true}).click();await f.page.getByRole('button',{name:'Match this job & improve',exact:true}).click();await f.page.getByRole('button',{name:'Optimize Resume',exact:true}).click();await f.page.getByRole('button',{name:'Apply All (2)',exact:true}).click();await f.page.locator('.rb-editor').getByText(after,{exact:false}).waitFor();assert(await f.page.locator('.rb-skills textarea').inputValue().then(v=>v.includes('MLflow')));await f.page.getByRole('button',{name:'Close AI Match'}).click();await f.page.frameLocator('iframe.rb-live').getByText(after,{exact:false}).first().waitFor();await f.page.getByRole('button',{name:'Undo',exact:true}).click();await f.page.locator('.rb-editor').getByText(before,{exact:false}).waitFor();assert.equal(f.calls.filter(c=>c.op==='save').length,0);const renders=f.calls.filter(c=>c.op==='render');for(const r of renders){assert.equal(r.body.headerTitle,'Backend Engineer');assert.equal(r.body.email,'locked@example.test');assert.equal(r.body.city,'Locked City');assert.equal(r.body.sections[0].role,'stony-brook');assert.deepEqual(r.body.sections[0].stack,['Python']);}assert.deepEqual(f.errors,[]);}finally{await f.close();}});
test('mobile review exposes Apply All without copy/paste and model dialog stays within viewport',async()=>{const f=await fixture(true);try{await f.page.goto(f.base+'/resume_builder?job=x');await f.page.getByRole('button',{name:'AI Help',exact:true}).click();await f.page.getByRole('button',{name:'Match this job & improve',exact:true}).click();await f.page.getByRole('button',{name:'Optimize Resume',exact:true}).click();const panel=f.page.getByRole('dialog',{name:'AI resume match'});await panel.getByRole('button',{name:'Apply All (2)',exact:true}).waitFor();const b=await panel.boundingBox();assert(b.x>=0&&b.width<=390);assert.deepEqual(f.errors,[]);}finally{await f.close();}});

test('general resume floating help is visible and answers a question without editing or saving',async()=>{const f=await fixture(true,true);try{await f.page.goto(f.base+'/resume_builder?track=data-analyst');const button=f.page.getByRole('button',{name:'AI Help',exact:true});await button.waitFor();const b=await button.boundingBox();assert(b.x>=0&&b.y+b.height<844);await button.click();await f.page.getByRole('button',{name:'Improve my general resume'}).waitFor();await f.page.getByRole('button',{name:'Ask a question',exact:true}).click();await f.page.getByLabel('What would you like to know?').fill('What skills do I demonstrate?');await f.page.getByRole('button',{name:'Ask AI',exact:true}).click();await f.page.getByText('Your current resume demonstrates Python experience.',{exact:true}).waitFor();assert.equal(f.calls.filter(c=>c.op==='save'||c.op==='ai-decision').length,0);assert.deepEqual(f.errors,[]);}finally{await f.close();}});

test('dashboard allowance shows provider percentage and measured session tokens separately',async()=>{const f=await fixture(true);try{await f.page.goto(f.base+'/resume_builder?job=x');await f.page.getByRole('button',{name:'✦ Codex 55% left',exact:true}).click();const panel=f.page.getByRole('region',{name:'AI usage'});await panel.getByText('1,200 tokens used',{exact:true}).waitFor();await panel.getByText('55% left',{exact:true}).waitFor();const b=await panel.boundingBox();assert(b.x>=0&&b.x+b.width<=390);await panel.getByText('Remaining allowance isn’t reported by this connection.',{exact:true}).waitFor();assert.deepEqual(f.errors,[]);}finally{await f.close();}});
test('card review deep link loads current resume and opens AI suggestions without saving',async()=>{const f=await fixture();try{await f.page.goto(f.base+'/resume_builder?job=https%3A%2F%2Fexample.test%2Fjob&ai=review');await f.page.getByRole('dialog',{name:'AI resume match'}).getByRole('button',{name:'Apply All (2)',exact:true}).waitFor();const calls=f.calls.filter(c=>c.op==='ai-match');assert.equal(calls.length,1);assert.equal(calls[0].body.sections[0].bullets[0].text,before);assert.equal(f.calls.filter(c=>c.op==='save'||c.op==='ai-decision').length,0);assert.deepEqual(f.errors,[]);}finally{await f.close();}});

test('staffing card opens AI review directly for existing resume; missing resume prepares before review',async()=>{for(const index of [0,1]){const f=await fixture();try{await f.page.goto(f.base+'/staffing');await f.page.getByRole('button',{name:'✦ Review with AI',exact:true}).nth(index).click();await f.page.getByRole('dialog',{name:'AI resume match'}).getByRole('button',{name:'Apply All (2)',exact:true}).waitFor();assert.equal(f.calls.filter(c=>c.op==='staffing-prepare').length,index);assert.match(f.page.url(),index?/pasted=prepared-resume&ai=review/:/job=.*&ai=review/);assert.equal(f.calls.filter(c=>c.op==='save').length,0);assert.deepEqual(f.errors,[]);}finally{await f.close();}}});
test('refresh resumes the same pending review and keeps approved draft without another generation',async()=>{const f=await fixture();let ready=false;const ids=[];let polls=0;const analysis={id:'persisted-analysis',original_match_score:60,optimized_match_score:75,subscores:{skills:60,experience:60,keywords:60,evidence:60},requirements:[],suggestions:[{id:'persisted-change',kind:'section',si:0,bi:-1,current:before,suggested:after,originalHashInput:JSON.stringify([{ac_id:'AC-001',facet:'default',text:before}]),bullets:[{ac_id:'AC-199',facet:'live-mlops',text:after}],reason:'Approved evidence',requirements:[],evidence_source:['story_bank:AC-199:0']}],atsProblems:[],resumeVersion:'rv',jdVersion:'jd1'};try{
 await f.page.route('**/resume-builder/ai-match',route=>{ids.push(route.request().postDataJSON().requestId);return route.fulfill({json:{ok:true,jobId:ids[0]}});});
 await f.page.route('**/resume-builder/ai-result',route=>{polls++;return route.fulfill({json:{ok:true,status:ready?'done':'running',stage:ready?'ready':'thinking',workerOnline:true,analysis:ready?analysis:undefined}});});
 await f.page.goto(f.base+'/resume_builder?job=x');await f.page.getByRole('button',{name:'AI Help',exact:true}).click();await f.page.getByLabel('AI provider').selectOption('codex');await f.page.getByRole('button',{name:'Match this job & improve'}).click();await f.page.getByText('Codex is thinking…',{exact:true}).waitFor();await f.page.reload();await f.page.getByText('Codex is thinking…',{exact:true}).waitFor();assert.equal(new Set(ids).size,1);assert(polls>=2);
 ready=true;await f.page.getByRole('button',{name:'Apply All (1)',exact:true}).click();const submitted=ids.length;await f.page.getByRole('button',{name:'Close AI Match'}).click();await f.page.locator('.rb-editor').getByText(after,{exact:false}).waitFor();assert.equal(ids.length,submitted);await f.page.reload();await f.page.getByText('No remaining rewrites. You can review the preview and save.',{exact:true}).waitFor();await f.page.locator('.rb-editor').getByText(after,{exact:false}).waitFor();assert.equal(new Set(ids).size,1);assert.equal(f.calls.filter(c=>c.op==='save').length,0);assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});
test('review summary presents all three sections and separates section ratings from job alignment',async()=>{const f=await fixture();try{await f.page.goto(f.base+'/resume_builder?job=x&ai=review');const summary=f.page.getByRole('region',{name:'Resume review summary'});await summary.getByRole('heading',{name:'Reviewed Experience, Skills and Projects'}).waitFor();const cards=summary.locator('article');assert.equal(await cards.count(),3);await cards.nth(0).getByText('Changes ready · 1',{exact:true}).waitFor();await cards.nth(1).getByText('Changes ready · 1',{exact:true}).waitFor();await cards.nth(2).getByText('Current wording kept',{exact:true}).waitFor();await summary.getByText(/not an ATS acceptance guarantee/).waitFor();assert.deepEqual(f.errors,[]);}finally{await f.close();}});

test('shared typography loads locally with readable editor and responsive viewport',async()=>{for(const mobile of [false,true]){const f=await fixture(mobile);try{await f.page.goto(f.base+'/resume_builder?job=x');await f.page.getByRole('button',{name:'AI Help',exact:true}).waitFor();await f.page.evaluate(()=>document.fonts.ready);const style=await f.page.evaluate(()=>({font:getComputedStyle(document.body).fontFamily,overflow:document.documentElement.scrollWidth>innerWidth,fontLoaded:[...document.fonts].some(f=>f.family==='Atriveo Sans'&&f.status==='loaded')}));assert.match(style.font,/Atriveo Sans/);assert.equal(style.overflow,false);assert.equal(style.fontLoaded,true);await f.page.frameLocator('iframe.rb-live').getByText('Locked Name',{exact:false}).first().waitFor();if(process.env.RESUME_THEME_SCREENSHOTS)await f.page.screenshot({path:`/private/tmp/atriveo-theme-${mobile?'mobile':'desktop'}.png`});assert.deepEqual(f.errors,[]);}finally{await f.close();}}});
